<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttachmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attachments')->delete();
        
        \DB::table('attachments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'attachable_type' => 'banners',
                'attachable_id' => 1,
                'path' => 'uploads/banners/1/image/image_1692279423835.jpg',
                'type' => 'image',
                'original_name' => 'aaaaa.jpg',
                'size' => '154283',
                'extension' => 'jpg',
                'created_at' => '2023-08-17 13:37:03',
                'updated_at' => '2023-08-17 13:37:03',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'attachable_type' => 'banners',
                'attachable_id' => 2,
                'path' => 'uploads/banners/2/image/image_1692279496393.jpg',
                'type' => 'image',
                'original_name' => 'rr.jfif',
                'size' => '10288',
                'extension' => 'jpg',
                'created_at' => '2023-08-17 13:38:16',
                'updated_at' => '2023-08-17 13:38:16',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/logo/logo_1692279500435.png',
                'type' => 'logo',
                'original_name' => 'logo-vision.png',
                'size' => '140153',
                'extension' => 'png',
                'created_at' => '2023-08-17 13:38:20',
                'updated_at' => '2023-08-17 13:38:20',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 1,
                'path' => 'uploads/services/1/icon/icon_1692279643902.png',
                'type' => 'icon',
                'original_name' => 'aa.png',
                'size' => '5861',
                'extension' => 'png',
                'created_at' => '2023-08-17 13:40:43',
                'updated_at' => '2023-08-17 13:40:43',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 2,
                'path' => 'uploads/services/2/icon/icon_1692279740770.png',
                'type' => 'icon',
                'original_name' => 'tt.png',
                'size' => '6395',
                'extension' => 'png',
                'created_at' => '2023-08-17 13:42:20',
                'updated_at' => '2023-08-17 13:42:20',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 1,
                'path' => 'uploads/company-projects/1/main_image/main_image_1692279971302.jpg',
                'type' => 'main_image',
                'original_name' => 'rr.jfif',
                'size' => '10288',
                'extension' => 'jpg',
                'created_at' => '2023-08-17 13:46:11',
                'updated_at' => '2023-08-21 13:32:26',
                'deleted_at' => '2023-08-21 13:32:26',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/organization_chart/organization_chart_1692341976231.png',
                'type' => 'organization_chart',
            'original_name' => 'VD - Logo (1).png',
                'size' => '2792',
                'extension' => 'png',
                'created_at' => '2023-08-18 06:59:36',
                'updated_at' => '2023-08-18 06:59:36',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/about_page_image/about_page_image_1692342139336.png',
                'type' => 'about_page_image',
            'original_name' => 'VD - Logo (1).png',
                'size' => '2792',
                'extension' => 'png',
                'created_at' => '2023-08-18 07:02:19',
                'updated_at' => '2023-08-18 07:02:19',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/about-files/about-files_1692342139562.png',
                'type' => 'about-files',
            'original_name' => 'VD - Logo (1).png',
                'size' => '2792',
                'extension' => 'png',
                'created_at' => '2023-08-18 07:02:19',
                'updated_at' => '2023-08-18 07:02:19',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'attachable_type' => 'clients',
                'attachable_id' => 1,
                'path' => 'uploads/clients/1/card_image/card_image_1692343575347.jpg',
                'type' => 'card_image',
                'original_name' => 'IMG-20230818-WA0001.jpg',
                'size' => '294961',
                'extension' => 'jpg',
                'created_at' => '2023-08-18 07:26:15',
                'updated_at' => '2023-08-18 07:26:15',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 3,
                'path' => 'uploads/services/3/icon/icon_1692509031867.png',
                'type' => 'icon',
                'original_name' => 'tt.png',
                'size' => '6395',
                'extension' => 'png',
                'created_at' => '2023-08-20 05:23:51',
                'updated_at' => '2023-08-20 05:23:51',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 3,
                'path' => 'uploads/services/3/image/image_1692514554180.jpg',
                'type' => 'image',
                'original_name' => 'appartment-building-appartments-architecture-87223-1-1.jpg',
                'size' => '205214',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 06:55:54',
                'updated_at' => '2023-08-20 06:55:54',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 2,
                'path' => 'uploads/services/2/image/image_1692514571132.jpg',
                'type' => 'image',
                'original_name' => 'Small-apartment-design.jpg',
                'size' => '145685',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 06:56:11',
                'updated_at' => '2023-08-20 06:56:11',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 1,
                'path' => 'uploads/services/1/image/image_1692514587495.jpg',
                'type' => 'image',
                'original_name' => 'images.jpg',
                'size' => '4950',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 06:56:27',
                'updated_at' => '2023-08-20 06:56:27',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 1,
                'attachable_type' => 'employees',
                'attachable_id' => NULL,
                'path' => 'uploads/employees//personal_photo/personal_photo_1692519989115.jpg',
                'type' => 'personal_photo',
                'original_name' => 'aaaaa.jpg',
                'size' => '154283',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 08:26:29',
                'updated_at' => '2023-08-20 08:26:29',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'attachable_type' => 'employees',
                'attachable_id' => NULL,
                'path' => 'uploads/employees//border_photo/border_photo_1692519989234.jpg',
                'type' => 'border_photo',
                'original_name' => 'aaaaa.jpg',
                'size' => '154283',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 08:26:29',
                'updated_at' => '2023-08-20 08:26:29',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'attachable_type' => 'employees',
                'attachable_id' => NULL,
                'path' => 'uploads/employees//passport_photo/passport_photo_1692519989567.jpg',
                'type' => 'passport_photo',
                'original_name' => 'rr.jfif',
                'size' => '10288',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 08:26:29',
                'updated_at' => '2023-08-20 08:26:29',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'attachable_type' => 'employees',
                'attachable_id' => NULL,
                'path' => 'uploads/employees//national_photo/national_photo_1692519989406.jpg',
                'type' => 'national_photo',
                'original_name' => 'rr.jfif',
                'size' => '10288',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 08:26:29',
                'updated_at' => '2023-08-20 08:26:29',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 1,
                'attachable_type' => 'Employee',
                'attachable_id' => 1,
                'path' => 'uploads/employee/1/acadmic/Acadmic_1692520091137.jpg',
                'type' => 'Acadmic',
                'original_name' => 'aaaaa.jpg',
                'size' => '154283',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 08:28:11',
                'updated_at' => '2023-08-20 08:28:11',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 1,
                'path' => 'uploads/news/1/image/image_1692521979791.jpg',
                'type' => 'image',
                'original_name' => '7ce3feb5-e38f-4516-9355-84582ce17f79.jpg',
                'size' => '291051',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 08:59:39',
                'updated_at' => '2023-08-20 08:59:39',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/organization_chart/organization_chart_1692522802672.pdf',
                'type' => 'organization_chart',
                'original_name' => 'sample.pdf',
                'size' => '3028',
                'extension' => 'pdf',
                'created_at' => '2023-08-20 09:13:22',
                'updated_at' => '2023-08-20 09:13:22',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 1,
                'path' => 'uploads/icons/1/logo/logo_1692523147524.png',
                'type' => 'logo',
                'original_name' => '01.png',
                'size' => '81837',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:19:07',
                'updated_at' => '2023-08-20 09:19:07',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 2,
                'path' => 'uploads/icons/2/logo/logo_1692523162581.png',
                'type' => 'logo',
                'original_name' => 'modon-logo-en.png',
                'size' => '19154',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:19:22',
                'updated_at' => '2023-08-20 09:19:22',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 3,
                'path' => 'uploads/icons/3/logo/logo_1692523173472.png',
                'type' => 'logo',
                'original_name' => 'nwc-saudi-01.png',
                'size' => '22157',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:19:33',
                'updated_at' => '2023-08-20 09:19:33',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 4,
                'path' => 'uploads/icons/4/logo/logo_1692523184575.png',
                'type' => 'logo',
                'original_name' => 'png-transparent-logo-amazon-com-brand-flipkart-others-text-orange-logo-thumbnail.png',
                'size' => '3689',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:19:44',
                'updated_at' => '2023-08-20 09:19:44',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 5,
                'path' => 'uploads/icons/5/logo/logo_1692523216187.png',
                'type' => 'logo',
            'original_name' => 'R (1).png',
                'size' => '75370',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:20:16',
                'updated_at' => '2023-08-20 09:20:16',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 6,
                'path' => 'uploads/icons/6/logo/logo_1692523233703.png',
                'type' => 'logo',
                'original_name' => 'R.png',
                'size' => '72518',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:20:33',
                'updated_at' => '2023-08-20 09:20:33',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 7,
                'path' => 'uploads/icons/7/logo/logo_1692523248788.png',
                'type' => 'logo',
                'original_name' => 'STC-Logo.png',
                'size' => '6979',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:20:48',
                'updated_at' => '2023-08-20 09:20:48',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 1,
                'path' => 'uploads/services/1/image/image_1692523339452.jpg',
                'type' => 'image',
                'original_name' => 'kl-main-building-d-Kopie-1024x576.jpg',
                'size' => '84063',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 09:22:19',
                'updated_at' => '2023-08-20 09:22:19',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 7,
                'path' => 'uploads/icons/7/logo/logo_1692523539224.png',
                'type' => 'logo',
                'original_name' => 'الأرصاد الجوية.png',
                'size' => '220620',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:25:39',
                'updated_at' => '2023-08-20 09:25:39',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 6,
                'path' => 'uploads/icons/6/logo/logo_1692523550719.png',
                'type' => 'logo',
                'original_name' => 'الدفاع المدني السعودي.png',
                'size' => '46650',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:25:50',
                'updated_at' => '2023-08-20 09:25:50',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 2,
                'path' => 'uploads/icons/2/logo/logo_1692523562555.png',
                'type' => 'logo',
                'original_name' => 'الطيران المدني.png',
                'size' => '142159',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:26:02',
                'updated_at' => '2023-08-20 09:26:02',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 8,
                'path' => 'uploads/icons/8/logo/logo_1692523578174.png',
                'type' => 'logo',
                'original_name' => 'المياه الوطنية.png',
                'size' => '57347',
                'extension' => 'png',
                'created_at' => '2023-08-20 09:26:18',
                'updated_at' => '2023-08-20 09:26:18',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 2,
                'path' => 'uploads/news/2/image/image_1692525333974.jpg',
                'type' => 'image',
                'original_name' => 'images.jpg',
                'size' => '4950',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 09:55:33',
                'updated_at' => '2023-08-20 09:55:33',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 4,
                'path' => 'uploads/icons/4/logo/logo_1692525355536.jpg',
                'type' => 'logo',
                'original_name' => 'appartment-building-appartments-architecture-87223-1-1.jpg',
                'size' => '205214',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 09:55:55',
                'updated_at' => '2023-08-20 09:55:55',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/organization_chart/organization_chart_1692525416395.pdf',
                'type' => 'organization_chart',
                'original_name' => 'sample.pdf',
                'size' => '3028',
                'extension' => 'pdf',
                'created_at' => '2023-08-20 09:56:56',
                'updated_at' => '2023-08-20 09:56:56',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 2,
                'path' => 'uploads/company-projects/2/main_image/main_image_1692528362246.jpg',
                'type' => 'main_image',
                'original_name' => 'aaaaa.jpg',
                'size' => '154283',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 10:46:02',
                'updated_at' => '2023-08-20 10:46:02',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/main_image/main_image_1692528453548.png',
                'type' => 'main_image',
                'original_name' => 'aa.png',
                'size' => '5861',
                'extension' => 'png',
                'created_at' => '2023-08-20 10:47:33',
                'updated_at' => '2023-08-21 12:46:10',
                'deleted_at' => '2023-08-21 12:46:10',
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 4,
                'path' => 'uploads/services/4/icon/icon_1692528689340.png',
                'type' => 'icon',
                'original_name' => 'tt.png',
                'size' => '6395',
                'extension' => 'png',
                'created_at' => '2023-08-20 10:51:29',
                'updated_at' => '2023-08-20 10:51:29',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 4,
                'path' => 'uploads/company-projects/4/main_image/main_image_1692528742357.png',
                'type' => 'main_image',
                'original_name' => 'tt.png',
                'size' => '6395',
                'extension' => 'png',
                'created_at' => '2023-08-20 10:52:22',
                'updated_at' => '2023-08-21 13:33:38',
                'deleted_at' => '2023-08-21 13:33:38',
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/main_image/main_image_1692529549237.jpg',
                'type' => 'main_image',
                'original_name' => 'Dubai_Marina_Skyline.jpg',
                'size' => '96185',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 11:05:49',
                'updated_at' => '2023-08-21 12:46:10',
                'deleted_at' => '2023-08-21 12:46:10',
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/main_image/main_image_1692529570701.jpg',
                'type' => 'main_image',
                'original_name' => 'kl-main-building-d-Kopie-1024x576.jpg',
                'size' => '84063',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 11:06:10',
                'updated_at' => '2023-08-21 12:46:10',
                'deleted_at' => '2023-08-21 12:46:10',
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/about_page_image/about_page_image_1692540164873.jpg',
                'type' => 'about_page_image',
                'original_name' => 'BUILD-LLC-Park-Modern-Night-01.jpg',
                'size' => '484730',
                'extension' => 'jpg',
                'created_at' => '2023-08-20 14:02:44',
                'updated_at' => '2023-08-20 14:02:44',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 1,
                'attachable_type' => 'icons',
                'attachable_id' => 4,
                'path' => 'uploads/icons/4/logo/logo_1692595634585.png',
                'type' => 'logo',
            'original_name' => 'R (1).png',
                'size' => '75370',
                'extension' => 'png',
                'created_at' => '2023-08-21 05:27:14',
                'updated_at' => '2023-08-21 05:27:14',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/about_page_image/about_page_image_1692608138390.jpg',
                'type' => 'about_page_image',
                'original_name' => 'appartment-building-appartments-architecture-87223-1-1.jpg',
                'size' => '205214',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 08:55:38',
                'updated_at' => '2023-08-21 08:55:38',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 1,
                'attachable_type' => 'messages',
                'attachable_id' => 202,
                'path' => 'uploads/users/messages/1/files/files_1692615660274.pdf',
                'type' => 'files',
                'original_name' => 'about-files_1692516606476.pdf',
                'size' => '165660',
                'extension' => 'pdf',
                'created_at' => '2023-08-21 11:01:00',
                'updated_at' => '2023-08-21 11:01:00',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 1,
                'attachable_type' => 'clients',
                'attachable_id' => 1,
                'path' => 'uploads/clients/1/image/image_1692616257197.jpg',
                'type' => 'image',
                'original_name' => 'Screenshot_2023-08-19-22-55-10-14.jpg',
                'size' => '16406',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 11:10:57',
                'updated_at' => '2023-08-21 11:10:57',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 1,
                'attachable_type' => 'clients',
                'attachable_id' => 1,
                'path' => 'uploads/clients/1/image/image_1692616691628.jpg',
                'type' => 'image',
                'original_name' => 'Screenshot_2023-08-20-14-33-51-40_d86989b64328e3aee918df92f2b0dfe6.jpg',
                'size' => '707638',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 11:18:11',
                'updated_at' => '2023-08-21 11:18:11',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image1/sub_image1_1692620918958.jpg',
                'type' => 'sub_image1',
                'original_name' => 'BUILD-LLC-Park-Modern-Night-01.jpg',
                'size' => '484730',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:28:38',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => '2023-08-21 12:46:41',
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image2/sub_image2_1692620918784.jpg',
                'type' => 'sub_image2',
                'original_name' => 'appartment-building-appartments-architecture-87223-1-1.jpg',
                'size' => '205214',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:28:38',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => '2023-08-21 12:46:41',
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image3/sub_image3_1692620918790.jpg',
                'type' => 'sub_image3',
                'original_name' => 'Small-apartment-design.jpg',
                'size' => '145685',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:28:38',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => '2023-08-21 12:46:41',
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image4/sub_image4_1692620918452.jpg',
                'type' => 'sub_image4',
                'original_name' => 'download.jpg',
                'size' => '11389',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:28:38',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => '2023-08-21 12:46:41',
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 1,
                'attachable_type' => 'clients',
                'attachable_id' => 1,
                'path' => 'uploads/clients/1/image/image_1692621154163.jpg',
                'type' => 'image',
                'original_name' => 'bfdbf259-8cc2-47ff-b448-ba595de558ec2079600162063183092.jpg',
                'size' => '1747763',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:32:34',
                'updated_at' => '2023-08-21 12:32:34',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 1,
                'attachable_type' => 'clients',
                'attachable_id' => 1,
                'path' => 'uploads/clients/1/image/image_1692621211373.jpg',
                'type' => 'image',
                'original_name' => '1000078397.jpg',
                'size' => '64509',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:33:31',
                'updated_at' => '2023-08-21 12:33:31',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image1/sub_image1_1692621842367.jpg',
                'type' => 'sub_image1',
                'original_name' => 'BUILD-LLC-Park-Modern-Night-01.jpg',
                'size' => '484730',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:44:02',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => '2023-08-21 12:46:41',
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image2/sub_image2_1692621842711.jpg',
                'type' => 'sub_image2',
                'original_name' => 'appartment-building-appartments-architecture-87223-1-1.jpg',
                'size' => '205214',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:44:02',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => '2023-08-21 12:46:41',
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image3/sub_image3_1692621842124.jpg',
                'type' => 'sub_image3',
                'original_name' => 'Small-apartment-design.jpg',
                'size' => '145685',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:44:02',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => '2023-08-21 12:46:41',
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image4/sub_image4_1692621842305.jpg',
                'type' => 'sub_image4',
                'original_name' => 'download.jpg',
                'size' => '11389',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:44:02',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => '2023-08-21 12:46:41',
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/main_image/main_image_1692621885865.jpg',
                'type' => 'main_image',
                'original_name' => 'kl-main-building-d-Kopie-1024x576.jpg',
                'size' => '84063',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:44:45',
                'updated_at' => '2023-08-21 12:46:10',
                'deleted_at' => '2023-08-21 12:46:10',
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/main_image/main_image_1692621970414.jpg',
                'type' => 'main_image',
                'original_name' => 'kl-main-building-d-Kopie-1024x576.jpg',
                'size' => '84063',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:46:10',
                'updated_at' => '2023-08-21 12:46:10',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image1/sub_image1_1692622001141.jpg',
                'type' => 'sub_image1',
                'original_name' => 'BUILD-LLC-Park-Modern-Night-01.jpg',
                'size' => '484730',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:46:41',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image2/sub_image2_1692622001872.jpg',
                'type' => 'sub_image2',
                'original_name' => 'appartment-building-appartments-architecture-87223-1-1.jpg',
                'size' => '205214',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:46:41',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image3/sub_image3_1692622001735.jpg',
                'type' => 'sub_image3',
                'original_name' => 'Small-apartment-design.jpg',
                'size' => '145685',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:46:41',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 3,
                'path' => 'uploads/company-projects/3/sub_image4/sub_image4_1692622001231.jpg',
                'type' => 'sub_image4',
                'original_name' => 'download.jpg',
                'size' => '11389',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 12:46:41',
                'updated_at' => '2023-08-21 12:46:41',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/logo/logo_1692624363156.png',
                'type' => 'logo',
                'original_name' => 'ماتريال.png',
                'size' => '273786',
                'extension' => 'png',
                'created_at' => '2023-08-21 13:26:03',
                'updated_at' => '2023-08-21 13:26:03',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/logo/logo_1692624527757.png',
                'type' => 'logo',
            'original_name' => 'VD - Logo (2).png',
                'size' => '245188',
                'extension' => 'png',
                'created_at' => '2023-08-21 13:28:47',
                'updated_at' => '2023-08-21 13:28:47',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 1,
                'path' => 'uploads/company-projects/1/main_image/main_image_1692624746997.png',
                'type' => 'main_image',
            'original_name' => 'image 4 (1).png',
                'size' => '295822',
                'extension' => 'png',
                'created_at' => '2023-08-21 13:32:26',
                'updated_at' => '2023-08-21 13:32:26',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 1,
                'path' => 'uploads/company-projects/1/sub_image1/sub_image1_1692624746874.jpg',
                'type' => 'sub_image1',
                'original_name' => 'backer-sha-ZC1go68bTic-unsplash.jpg',
                'size' => '1333192',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 13:32:26',
                'updated_at' => '2023-08-21 13:32:26',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 1,
                'path' => 'uploads/company-projects/1/sub_image2/sub_image2_1692624746585.png',
                'type' => 'sub_image2',
                'original_name' => 'image 5.png',
                'size' => '912206',
                'extension' => 'png',
                'created_at' => '2023-08-21 13:32:26',
                'updated_at' => '2023-08-21 13:32:26',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 4,
                'path' => 'uploads/company-projects/4/main_image/main_image_1692624818334.png',
                'type' => 'main_image',
                'original_name' => 'image 5.png',
                'size' => '912206',
                'extension' => 'png',
                'created_at' => '2023-08-21 13:33:38',
                'updated_at' => '2023-08-21 13:33:38',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 4,
                'path' => 'uploads/services/4/image/image_1692625057797.jpg',
                'type' => 'image',
                'original_name' => 'Types-of-building-materials.jpg',
                'size' => '117621',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 13:37:38',
                'updated_at' => '2023-08-22 18:39:31',
                'deleted_at' => '2023-08-22 18:39:31',
            ),
            71 => 
            array (
                'id' => 72,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/about_page_image/about_page_image_1692634493580.jpg',
                'type' => 'about_page_image',
                'original_name' => 'Capture.JPG',
                'size' => '40118',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 16:14:53',
                'updated_at' => '2023-08-21 16:14:53',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 2,
                'path' => 'uploads/news/2/image/image_1692635973864.jpg',
                'type' => 'image',
                'original_name' => 'ابوريان.JPG',
                'size' => '30279',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 16:39:33',
                'updated_at' => '2023-08-21 16:39:33',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 1,
                'path' => 'uploads/news/1/image/image_1692636901368.jpg',
                'type' => 'image',
                'original_name' => 'محسن.JPG',
                'size' => '13573',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 16:55:01',
                'updated_at' => '2023-08-21 16:55:01',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 3,
                'path' => 'uploads/news/3/image/image_1692637343179.jpg',
                'type' => 'image',
                'original_name' => 'image_1692521979791.jpg',
                'size' => '291051',
                'extension' => 'jpg',
                'created_at' => '2023-08-21 17:02:23',
                'updated_at' => '2023-08-21 17:02:23',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/organization_chart/organization_chart_1692637761968.odp',
                'type' => 'organization_chart',
                'original_name' => 'Untitled 2.odp',
                'size' => '20867',
                'extension' => 'odp',
                'created_at' => '2023-08-21 17:09:21',
                'updated_at' => '2023-08-21 17:09:21',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/organization_chart/organization_chart_1692637777924.ico',
                'type' => 'organization_chart',
                'original_name' => 'favicon.ico',
                'size' => '11262',
                'extension' => 'ico',
                'created_at' => '2023-08-21 17:09:37',
                'updated_at' => '2023-08-21 17:09:37',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'user_id' => 4,
                'attachable_type' => 'clients',
                'attachable_id' => 4,
                'path' => 'uploads/clients/4/register_image/register_image_1692685966456.jpg',
                'type' => 'register_image',
                'original_name' => '1000000038.jpg',
                'size' => '99912',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 06:32:46',
                'updated_at' => '2023-08-22 06:32:46',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 5,
                'path' => 'uploads/company-projects/5/main_image/main_image_1692704253851.jpg',
                'type' => 'main_image',
                'original_name' => 'kl-main-building-d-Kopie-1024x576.jpg',
                'size' => '84063',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:37:33',
                'updated_at' => '2023-08-22 11:37:33',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 6,
                'path' => 'uploads/company-projects/6/main_image/main_image_1692704254135.jpg',
                'type' => 'main_image',
                'original_name' => 'kl-main-building-d-Kopie-1024x576.jpg',
                'size' => '84063',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:37:34',
                'updated_at' => '2023-08-22 11:37:34',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 7,
                'path' => 'uploads/company-projects/7/main_image/main_image_1692704492499.jpg',
                'type' => 'main_image',
                'original_name' => '42442.jpg',
                'size' => '100803',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:41:32',
                'updated_at' => '2023-08-22 11:41:32',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 8,
                'path' => 'uploads/company-projects/8/main_image/main_image_1692704523192.jpg',
                'type' => 'main_image',
                'original_name' => 'kl-main-building-d-Kopie-1024x576.jpg',
                'size' => '84063',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:42:03',
                'updated_at' => '2023-08-22 11:42:03',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 8,
                'path' => 'uploads/company-projects/8/sub_image1/sub_image1_1692705226711.png',
                'type' => 'sub_image1',
                'original_name' => 'group.png',
                'size' => '22007',
                'extension' => 'png',
                'created_at' => '2023-08-22 11:53:46',
                'updated_at' => '2023-08-22 11:53:46',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 8,
                'path' => 'uploads/company-projects/8/sub_image2/sub_image2_1692705226154.jpg',
                'type' => 'sub_image2',
                'original_name' => 'easter.jpg',
                'size' => '1812651',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:53:46',
                'updated_at' => '2023-08-22 11:53:46',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 8,
                'path' => 'uploads/company-projects/8/sub_image3/sub_image3_1692705226879.png',
                'type' => 'sub_image3',
                'original_name' => 'post-033.png',
                'size' => '1188521',
                'extension' => 'png',
                'created_at' => '2023-08-22 11:53:47',
                'updated_at' => '2023-08-22 11:53:47',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 8,
                'path' => 'uploads/company-projects/8/sub_image4/sub_image4_1692705227621.jpg',
                'type' => 'sub_image4',
                'original_name' => 'IMG-20230527-WA0034.jpg',
                'size' => '481986',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:53:47',
                'updated_at' => '2023-08-22 11:53:47',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 9,
                'path' => 'uploads/company-projects/9/main_image/main_image_1692705252359.jpg',
                'type' => 'main_image',
                'original_name' => 'Types-of-building-materials.jpg',
                'size' => '117621',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:54:12',
                'updated_at' => '2023-08-22 11:54:12',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 9,
                'path' => 'uploads/company-projects/9/sub_image1/sub_image1_1692705252825.jpg',
                'type' => 'sub_image1',
                'original_name' => 'Types-of-building-materials.jpg',
                'size' => '117621',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:54:12',
                'updated_at' => '2023-08-22 11:54:12',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 9,
                'path' => 'uploads/company-projects/9/sub_image2/sub_image2_1692705252133.jpg',
                'type' => 'sub_image2',
                'original_name' => 'Types-of-building-materials.jpg',
                'size' => '117621',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:54:12',
                'updated_at' => '2023-08-22 11:54:12',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 9,
                'path' => 'uploads/company-projects/9/sub_image3/sub_image3_1692705252354.jpg',
                'type' => 'sub_image3',
                'original_name' => 'Types-of-building-materials.jpg',
                'size' => '117621',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:54:12',
                'updated_at' => '2023-08-22 11:54:12',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 9,
                'path' => 'uploads/company-projects/9/sub_image4/sub_image4_1692705252139.jpg',
                'type' => 'sub_image4',
                'original_name' => 'Types-of-building-materials.jpg',
                'size' => '117621',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:54:12',
                'updated_at' => '2023-08-22 11:54:12',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 10,
                'path' => 'uploads/company-projects/10/main_image/main_image_1692705329619.jpg',
                'type' => 'main_image',
                'original_name' => 'BUILD-LLC-Park-Modern-Night-01.jpg',
                'size' => '484730',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:55:29',
                'updated_at' => '2023-08-22 11:55:29',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 10,
                'path' => 'uploads/company-projects/10/sub_image1/sub_image1_1692705329494.jpg',
                'type' => 'sub_image1',
                'original_name' => 'girl_pose_smile_1011693_1920x1080.jpg',
                'size' => '218829',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:55:29',
                'updated_at' => '2023-08-22 11:55:29',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 10,
                'path' => 'uploads/company-projects/10/sub_image2/sub_image2_1692705329780.jpg',
                'type' => 'sub_image2',
                'original_name' => 'privacy.jpg',
                'size' => '7966',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:55:29',
                'updated_at' => '2023-08-22 11:55:29',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 10,
                'path' => 'uploads/company-projects/10/sub_image3/sub_image3_1692705329426.jpg',
                'type' => 'sub_image3',
                'original_name' => 'Modern-apartment-units-inside-heritage-building-Down-Under.jpg',
                'size' => '335869',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:55:29',
                'updated_at' => '2023-08-22 11:55:29',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 10,
                'path' => 'uploads/company-projects/10/sub_image4/sub_image4_1692705329820.jpg',
                'type' => 'sub_image4',
                'original_name' => 'wolf_moon_night_150508_1920x1080.jpg',
                'size' => '379804',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 11:55:29',
                'updated_at' => '2023-08-22 11:55:29',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/organization_chart/organization_chart_1692710178410.pdf',
                'type' => 'organization_chart',
                'original_name' => 'ملاحظات الموقع.pdf',
                'size' => '1216087',
                'extension' => 'pdf',
                'created_at' => '2023-08-22 13:16:18',
                'updated_at' => '2023-08-22 13:16:18',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'user_id' => 1,
                'attachable_type' => 'website',
                'attachable_id' => 0,
                'path' => 'uploads/website/0/organization_chart/organization_chart_1692710214234.jpg',
                'type' => 'organization_chart',
                'original_name' => '7ce3feb5-e38f-4516-9355-84582ce17f79.jpg',
                'size' => '291051',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 13:16:54',
                'updated_at' => '2023-08-22 13:16:54',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 4,
                'path' => 'uploads/news/4/image/image_1692711286363.jpg',
                'type' => 'image',
                'original_name' => 'Types-of-building-materials.jpg',
                'size' => '117621',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 13:34:46',
                'updated_at' => '2023-08-22 13:34:46',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 5,
                'path' => 'uploads/news/5/image/image_1692711356187.png',
                'type' => 'image',
                'original_name' => 'group.png',
                'size' => '22007',
                'extension' => 'png',
                'created_at' => '2023-08-22 13:35:56',
                'updated_at' => '2023-08-22 13:35:56',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 11,
                'path' => 'uploads/company-projects/11/main_image/main_image_1692725027206.jpg',
                'type' => 'main_image',
                'original_name' => '1.jpg',
                'size' => '5456930',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 17:23:47',
                'updated_at' => '2023-08-22 17:23:47',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 11,
                'path' => 'uploads/company-projects/11/sub_image1/sub_image1_1692725027701.jpg',
                'type' => 'sub_image1',
                'original_name' => '9.jpg',
                'size' => '4850367',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 17:23:47',
                'updated_at' => '2023-08-22 17:23:47',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 11,
                'path' => 'uploads/company-projects/11/sub_image2/sub_image2_1692725027817.jpg',
                'type' => 'sub_image2',
                'original_name' => '10-.jpg',
                'size' => '4422485',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 17:23:47',
                'updated_at' => '2023-08-22 17:23:47',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 11,
                'path' => 'uploads/company-projects/11/sub_image3/sub_image3_1692725027348.jpg',
                'type' => 'sub_image3',
                'original_name' => '14.jpg',
                'size' => '6532412',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 17:23:47',
                'updated_at' => '2023-08-22 17:23:47',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'user_id' => 1,
                'attachable_type' => 'company-projects',
                'attachable_id' => 11,
                'path' => 'uploads/company-projects/11/sub_image4/sub_image4_1692725027465.jpg',
                'type' => 'sub_image4',
                'original_name' => '9-.jpg',
                'size' => '4937393',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 17:23:47',
                'updated_at' => '2023-08-22 17:23:47',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 4,
                'path' => 'uploads/services/4/image/image_1692729571803.jpg',
                'type' => 'image',
                'original_name' => '3d-architectural-design.jpg',
                'size' => '87876',
                'extension' => 'jpg',
                'created_at' => '2023-08-22 18:39:31',
                'updated_at' => '2023-08-22 18:39:31',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 5,
                'path' => 'uploads/services/5/image/image_1692730346176.png',
                'type' => 'image',
                'original_name' => 'sustainable-development.png',
                'size' => '298015',
                'extension' => 'png',
                'created_at' => '2023-08-22 18:52:26',
                'updated_at' => '2023-08-22 18:52:26',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'user_id' => 1,
                'attachable_type' => 'services',
                'attachable_id' => 5,
                'path' => 'uploads/services/5/icon/icon_1692730346456.png',
                'type' => 'icon',
                'original_name' => 'Dr.-Eisa-Al-Hartany-Environmental-Consulting-Office-210.png',
                'size' => '29861',
                'extension' => 'png',
                'created_at' => '2023-08-22 18:52:26',
                'updated_at' => '2023-08-22 18:52:26',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 1,
                'path' => 'uploads/news/1/image/image_1692788306475.jpg',
                'type' => 'image',
                'original_name' => '1efe46f1-c627-4ac6-ab6a-de42cc4e586c.jpg',
                'size' => '355791',
                'extension' => 'jpg',
                'created_at' => '2023-08-23 10:58:26',
                'updated_at' => '2023-08-23 10:58:26',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 2,
                'path' => 'uploads/news/2/image/image_1692788352407.jpg',
                'type' => 'image',
                'original_name' => 'car_motorcycle_garage_114811_1920x1080.jpg',
                'size' => '259997',
                'extension' => 'jpg',
                'created_at' => '2023-08-23 10:59:12',
                'updated_at' => '2023-08-23 10:59:12',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'user_id' => 1,
                'attachable_type' => 'news',
                'attachable_id' => 3,
                'path' => 'uploads/news/3/image/image_1692788640607.jpg',
                'type' => 'image',
                'original_name' => 'car_motorcycle_garage_114811_1920x1080.jpg',
                'size' => '259997',
                'extension' => 'jpg',
                'created_at' => '2023-08-23 11:04:00',
                'updated_at' => '2023-08-23 11:04:00',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}